[platformio]
default_envs = m5dial

[env:m5dial]
platform = espressif32
framework = arduino
board = m5stack-stamps3
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
extra_scripts =
    pre:tools/build_webui.py
lib_deps =
    m5stack/M5Dial @ ^1.0.3
    bblanchon/ArduinoJson @ ^6.21.5
